export { SPEEDS } from './tts/catalog'
export type { TtsVoice, TtsLanguage } from './tts/catalog'
export { REFERENCE_LANGUAGES, SPEED_OPTIONS, SPEED_STEP, defaultVoiceByLanguage, defaultGroupByLanguage, getVoiceGroups, getVoiceOptions, voiceForSelection, toWrittenLang, SPOKEN_GROUP } from './tts/catalog'
export type { TtsSegment, HighlightRange, TtsBoundary, EdgeBoundaryEvent } from './tts/segment'
export { parseEdgeMetadata, splitTtsSegments, splitHighlightRanges, activeHighlightRange } from './tts/segment'
